SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `Projeto` DEFAULT CHARACTER SET utf8;
USE `Projeto` ;

CREATE TABLE IF NOT EXISTS `Projeto`.`Produto` (
	`NomeVendedor` VARCHAR(45) NOT NULL,
    `Telefone` VARCHAR(15) NOT NULL,
	`NomeProduto` VARCHAR(45) NOT NULL,
    `Tipo` VARCHAR(17) NOT NULL,
    `Valor` FLOAT,
    `Gratis` BOOLEAN,
    `idProduto` INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;